In [ ]:
import pandas as pd
import os

print("Setting up file paths...")

DATA_DIR = 'data'
LISTINGS_FILE = os.path.join(DATA_DIR, 'chicago_airbnb_listings.csv')
REVIEWS_FILE = os.path.join(DATA_DIR, 'chicago_airbnb_reviews.csv')
NEIGHBORHOODS_FILE = os.path.join(DATA_DIR, 'chicago_airbnb_neighbourhoods.csv')
OUTPUT_FILE = os.path.join(DATA_DIR, 'integrated_chicago_data.csv')

print(f"Data folder: {os.path.abspath(DATA_DIR)}")
print("Setup complete.")

Setting up file paths...
Data folder: /Users/jjpark/Desktop/UIUC/Fall 2025/IS 477/project/data
Setup complete.

In [2]:
print("Loading datasets...")
try:
    listings = pd.read_csv(LISTINGS_FILE)
    reviews = pd.read_csv(REVIEWS_FILE)
    neighborhoods = pd.read_csv(NEIGHBORHOODS_FILE)
    print("Files loaded successfully!")
    
    # This is the magic of notebooks: you can see your data
    listings.head()

except FileNotFoundError as e:
    print("\n*** ERROR: Could not find files. ***")
    print(f"Error details: {e}")
    print(f"Please make sure your 3 CSV files are in the 'data' folder: {os.path.abspath(DATA_DIR)}")

Loading datasets...
Files loaded successfully!

In [3]:
print("Step 1/2: Merging Listings and Reviews...")
integrated_data = pd.merge(
    listings,
    reviews,
    left_on='id',
    right_on='listing_id',
    how='left',
    suffixes=('_listing', '_review')
)
print("Merge 1 complete.")
integrated_data.head()

Step 1/2: Merging Listings and Reviews...
Merge 1 complete.

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,listing_id,date
0,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,3,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-01-09
1,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,3,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-03-24
2,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,3,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-04-30
3,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,3,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-05-04
4,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,3,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-05-10

In [4]:
print("Step 2/2: Merging Neighborhood data...")
final_integrated_data = pd.merge(
    integrated_data,
    neighborhoods,
    on='neighbourhood',
    how='left',
    suffixes=('', '_neighborhood')
)
print("Merge 2 complete.")
final_integrated_data.head()

Step 2/2: Merging Neighborhood data...
Merge 2 complete.

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,listing_id,date,neighbourhood_group_neighborhood
0,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,...,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-01-09,NaN
1,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,...,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-03-24,NaN
2,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,...,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-04-30,NaN
3,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,...,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-05-04,NaN
4,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.7879,-87.5878,Private room,113.0,...,253,2025-06-08,1.99,1,341,11,R17000015609,2384.0,2015-05-10,NaN

In [5]:
print(f"Saving final integrated data to {OUTPUT_FILE}...")
final_integrated_data.to_csv(OUTPUT_FILE, index=False)
print(f"All done! File saved successfully to: {os.path.abspath(OUTPUT_FILE)}")

Saving final integrated data to data/integrated_chicago_data.csv...
All done! File saved successfully to: /Users/jjpark/Desktop/UIUC/Fall 2025/IS 477/project/data/integrated_chicago_data.csv